// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device.proto

/*
Package plugin_manager is a generated protocol buffer package.

It is generated from these files:
	device.proto

It has these top-level messages:
	Empty
	Integer
	Devices
	Device
	TopologyInfo
	NUMANode
*/
package plugin_manager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Integer struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Integer) Reset()                    { *m = Integer{} }
func (m *Integer) String() string            { return proto.CompactTextString(m) }
func (*Integer) ProtoMessage()               {}
func (*Integer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Integer) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Devices struct {
	Device []*Device `protobuf:"bytes,1,rep,name=device" json:"device,omitempty"`
}

func (m *Devices) Reset()                    { *m = Devices{} }
func (m *Devices) String() string            { return proto.CompactTextString(m) }
func (*Devices) ProtoMessage()               {}
func (*Devices) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Devices) GetDevice() []*Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type Device struct {
	// A unique ID assigned by the device plugin used
	// to identify devices during the communication
	// Max length of this field is 63 characters
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	// Health of the device, can be healthy or unhealthy, see constants.go
	Health string `protobuf:"bytes,2,opt,name=health" json:"health,omitempty"`
	// Topology for device
	Topology *TopologyInfo `protobuf:"bytes,3,opt,name=topology" json:"topology,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Device) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Device) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *Device) GetTopology() *TopologyInfo {
	if m != nil {
		return m.Topology
	}
	return nil
}

type TopologyInfo struct {
	Nodes []*NUMANode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *TopologyInfo) Reset()                    { *m = TopologyInfo{} }
func (m *TopologyInfo) String() string            { return proto.CompactTextString(m) }
func (*TopologyInfo) ProtoMessage()               {}
func (*TopologyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TopologyInfo) GetNodes() []*NUMANode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NUMANode struct {
	ID int64 `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *NUMANode) Reset()                    { *m = NUMANode{} }
func (m *NUMANode) String() string            { return proto.CompactTextString(m) }
func (*NUMANode) ProtoMessage()               {}
func (*NUMANode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NUMANode) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "plugin_manager.Empty")
	proto.RegisterType((*Integer)(nil), "plugin_manager.Integer")
	proto.RegisterType((*Devices)(nil), "plugin_manager.Devices")
	proto.RegisterType((*Device)(nil), "plugin_manager.Device")
	proto.RegisterType((*TopologyInfo)(nil), "plugin_manager.TopologyInfo")
	proto.RegisterType((*NUMANode)(nil), "plugin_manager.NUMANode")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0x49, 0x4b, 0xdb, 0x7d, 0xdf, 0x8e, 0x1e, 0xc2, 0xd7, 0x59, 0x86, 0x60, 0xc9, 0xa9,
	0xa7, 0x22, 0xf5, 0xa2, 0x17, 0x7f, 0xb0, 0x8a, 0x14, 0x74, 0x48, 0x51, 0x3c, 0x4a, 0x5c, 0x63,
	0x5b, 0xc9, 0x92, 0xd2, 0x66, 0x83, 0xfd, 0x99, 0xfe, 0x47, 0x62, 0xd3, 0xc9, 0x56, 0x3c, 0xe8,
	0xf1, 0x7d, 0xde, 0x87, 0x4f, 0x9e, 0x3c, 0x09, 0x8c, 0x73, 0xb6, 0xae, 0x16, 0x2c, 0xaa, 0x1b,
	0xa9, 0x24, 0xf6, 0x6a, 0xbe, 0x2a, 0x2a, 0xf1, 0xb2, 0xa4, 0x82, 0x16, 0xac, 0x21, 0x0e, 0x58,
	0x37, 0xcb, 0x5a, 0x6d, 0xc8, 0x31, 0x38, 0xa9, 0x50, 0xac, 0x60, 0x0d, 0xfe, 0x0f, 0xd6, 0x9a,
	0xf2, 0x15, 0xf3, 0x51, 0x80, 0x42, 0x2b, 0xd3, 0x03, 0x39, 0x07, 0x27, 0xe9, 0x48, 0x2d, 0x8e,
	0xc0, 0xd6, 0x50, 0x1f, 0x05, 0x66, 0xe8, 0xc6, 0x93, 0x68, 0x9f, 0x1a, 0x69, 0x63, 0xd6, 0xbb,
	0xc8, 0x3b, 0xd8, 0x5a, 0xc1, 0x1e, 0x18, 0x69, 0xd2, 0x71, 0xff, 0x65, 0x46, 0x95, 0xe0, 0x09,
	0xd8, 0x25, 0xa3, 0x5c, 0x95, 0xbe, 0xd1, 0x69, 0xfd, 0x84, 0xcf, 0x60, 0xa4, 0x64, 0x2d, 0xb9,
	0x2c, 0x36, 0xbe, 0x19, 0xa0, 0xd0, 0x8d, 0x8f, 0x86, 0x67, 0x3c, 0xf6, 0xfb, 0x54, 0xbc, 0xc9,
	0xec, 0xdb, 0x4d, 0x2e, 0x60, 0xbc, 0xbb, 0xc1, 0x11, 0x58, 0x42, 0xe6, 0xac, 0xed, 0xa3, 0xfa,
	0x43, 0xcc, 0xfc, 0xe9, 0xfe, 0x7a, 0x2e, 0x73, 0x96, 0x69, 0x1b, 0x99, 0xc2, 0x68, 0x2b, 0xed,
	0xa4, 0x35, 0xbf, 0xd2, 0xc6, 0x1f, 0x08, 0x60, 0x46, 0x39, 0x9f, 0xf1, 0x8a, 0x09, 0x85, 0xaf,
	0xc0, 0xbb, 0x65, 0x4a, 0xdf, 0xec, 0x81, 0x36, 0xaa, 0xc5, 0x07, 0x43, 0x7a, 0xd7, 0xed, 0xf4,
	0xf0, 0xe7, 0x7e, 0xda, 0x3d, 0xc2, 0x9d, 0xa4, 0xf9, 0xef, 0x09, 0xdb, 0xb7, 0xba, 0x04, 0xf7,
	0x99, 0xaa, 0x45, 0xd9, 0xf7, 0xfb, 0xc7, 0x00, 0x27, 0xe8, 0xd5, 0xee, 0xfe, 0xc5, 0xe9, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x12, 0xf2, 0x3c, 0x27, 0x02, 0x00, 0x00,
}
